### ISSUE TITLE
archive export labels with slash

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#1021]
Exporting archives is not possible when Element labels contain '/'. Better escaping is needed.

```python
import holoviews as hv
hv.notebook_extension()
hv.archive.auto()
hv.Curve([1,1], label='./test')
hv.archive.export()
hv.archive.last_export_status()
```

```
The last call to holoviews.archive.export was unsuccessful.

Traceback (most recent call last):
  File "/home/tenner/src/holoviews/holoviews/ipython/archive.py", line 273, in _export_with_html
    info={'notebook':self.notebook_name})
  File "/home/tenner/src/holoviews/holoviews/core/io.py", line 807, in export
    self._directory_archive(export_name, files, root)
  File "/home/tenner/src/holoviews/holoviews/core/io.py", line 747, in _directory_archive
    with open(fpath, 'wb') as f:
IOError: [Errno 2] No such file or directory: '/media/data2/tenner/data/ipython-notebooks/Tests/Test_holoviews_export/Curve-./test.svg'
```

**Comment by jbednar** [comment]
Should also check backslashes, on Windows.

**Comment by jlstevens** [comment]
This has been addressed by the above PR (merged).
