### ISSUE TITLE
Bokeh unit test failure relating to color strings

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1460]
With a recent version of bokeh installed, running:
```
nosetests  -a  '!optional' testplotinstantiation.py
```

Results in this failure:

```
.................................................................................F.....................................................S.
======================================================================
FAIL: test_points_color_selection_nonselection (tests.testplotinstantiation.TestBokehPlotInstantiation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jstevens/Desktop/development/holoviews/tests/testplotinstantiation.py", line 691, in test_points_color_selection_nonselection
    self.assertEqual(glyph_renderer.glyph.fill_color, 'green')
  File "/Users/jstevens/Desktop/development/holoviews/holoviews/element/comparison.py", line 81, in assertEqual
    asserter(first, second)
  File "/Users/jstevens/Desktop/development/holoviews/holoviews/element/comparison.py", line 58, in simple_equality
    raise cls.failureException(msg or standardMsg)
AssertionError: '#008000' != 'green'
```

Apparently the behavior on travis is different as the tests are passing there.

**Comment by philippjfr** [comment]
These are resolved now we've updated to latest bokeh on travis.
