### ISSUE TITLE
Example apps nytaxi_hover.py & game_of_life.py NameError with Holoviews 1.9.0

### ISSUE THREAD

**Issue by Huite** [ioam/holoviews#2115]
I've been playing around with the Bokeh App examples found at : https://github.com/ioam/holoviews/tree/master/examples/gallery/apps/bokeh
and nytaxi_hover.py and game_of_life.py give me a NameError when I call them with `bokeh serve --show`; the other examples work without a hitch. 

I get the following error:

```
(ds) p:\holoviews_visualization>bokeh serve --show conway_life.py
2017-11-11 21:16:30,057 Starting Bokeh server version 0.12.11dev3 (running on Tornado 4.5.2)
2017-11-11 21:16:30,073 Bokeh app running at: http://localhost:5006/conway_life
2017-11-11 21:16:30,073 Starting Bokeh server with process id: 2884
2017-11-11 21:16:53,986 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x00000000059C2B38>: name 'bokeh_
version' is not defined
File "callbacks.py", line 422, in set_server_callback:
if self.on_events and bokeh_version >= '0.12.5': Traceback (most recent call last):
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\bokeh\application\handlers\code_runner.py", line 125, in run exec(self._code, module.__dict__)
  File "p:\holoviews_visualization\conway_life.py", line 79, in <module>
    doc = renderer.server_doc(dmap.redim.range(z=(0, 1)).opts(**opts))
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\bokeh\renderer.py", line 198, in server_doc
    plot, _ =  renderer._validate(obj, 'auto')
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\renderer.py", line 194, in _validate plot = self.get_plot(obj, renderer=self)
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\bokeh\renderer.py", line 117, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer)
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\renderer.py", line 181, in get_plot
    plot.update(0)
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\plot.py", line 486, in update
    item = self.__getitem__(key)
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\plot.py", line 221, in __getitem__
    if not self.drawn: self.handles['fig'] = self.initialize_plot()
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\bokeh\element.py", line 789, in initialize_plot cb.initialize()
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 511, in initialize self.set_server_callback(handle)
  File "p:\holoviews_visualization\Miniconda\envs\ds\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 422, in set_server_callback
    if self.on_events and bokeh_version >= '0.12.5':
NameError: name 'bokeh_version' is not defined

2017-11-11 21:16:54,169 200 GET /conway_life (::1) 23589.36ms
2017-11-11 21:16:54,552 101 GET /conway_life/ws?bokeh-protocol-version=1.0&bokeh-session-id=1kpcThe7ZDWFzib3dFkZvthB5sj1qZeOrrVOpNdURlA4 (::1) 1.00ms
2017-11-11 21:16:54,552 WebSocket connection opened
2017-11-11 21:16:54,553 ServerConnection created
2017-11-11 21:16:54,562 404 GET /favicon.ico (::1) 0.00ms
```

I'm using Python 3.6, with Holoviews 1.9.0 and Bokeh 0.12.10. When I downgrade to Holoviews 1.8.3 and Bokeh 0.12.9, all examples work again.

(Incidentally, I wanted to use `regrid` with `from holoviews.operation.datashader`, which requires Holoviews 1.9.0. However, through some weird winding path I accidentally ended up with conda installing Holoviews 1.8.4-69-g50182b78. This seems to include `regrid`, and it plays nice with Bokeh 0.12.9, so I think I'm alright for the time being.)

By the way, I absolutely love your work: the ease of use and versatility of Holoviews + Datashader + Bokeh/Matplotlib is nothing  short of amazing!

**Comment by philippjfr** [comment]
Thanks for reporting this. The fix for this is already in master, and we're hoping to have a 1.9.1 release tomorrow.

>By the way, I absolutely love your work: the ease of use and versatility of Holoviews + Datashader + Bokeh/Matplotlib is nothing short of amazing!

Thanks for the kind words, it means a lot!

**Comment by Huite** [comment]
> The fix for this is already in master, and we're hoping to have a 1.9.1 release tomorrow.
Ha, fantastic! I'll make sure to upgrade once it's out.
