### ISSUE TITLE
DynamicMap Overlay error message when using .opts()

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#2284]
```
d=pd.DataFrame( {'x':[1,2,3],'y':[4,8,12]})
origin=(0,0)
def plot(N):
    h = hv.Scatter(d,'x','y')*\
         hv.Scatter((origin)).opts(style=dict(marker='d',size=10,color='red'))*\
        hv.Curve( np.linspace(0,3,N)**2)
    return h
hv.DynamicMap( plot, kdims='N').redim.values(N=[2,3])
```
yields
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/plotting/util.py", line 249, in get_plot_frame
    return map_obj[key]
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/core/spaces.py", line 1030, in __getitem__
    self._cache(tuple_key, val)
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/core/spaces.py", line 1077, in _cache
    self[key] = val
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/core/ndmapping.py", line 520, in __setitem__
    self._add_item(key, value, update=False)
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/core/ndmapping.py", line 157, in _add_item
    self._item_check(dim_vals, data)
  File "/usr/lib/python3.6/site-packages/holoviews-1.9.2-py3.6.egg/holoviews/core/ndmapping.py", line 821, in _item_check
    (self.__class__.__name__, type(data).__name__, self.type.__name__))
AssertionError: DynamicMap must only contain one type of object, not both Overlay and Scatter.
```
the error message disappears if `.opts()` is removed

**Comment by philippjfr** [comment]
I believe this will be resolved by implementing https://github.com/ioam/holoviews/issues/2254.

**Comment by philippjfr** [comment]
Appears to be fixed in master already.
