### ISSUE TITLE
Bug: Value error when using redim to set dimensions on App

### ISSUE THREAD

**Issue by fccoelho** [ioam/holoviews#2301]
I am trying to make the following DynamicMap plot work in an app. It works perfectly on a notebook.

```python
def rolling_means_outliers(exchange, symbol, w):
    df = get_test_data(1)
    df['date'] = df.index
    curve = hv.Curve(df, ('date', 'Date'), ('close', 'Close price')).opts(plot=dict(tools=['box_select']))
    return curve * rolling(curve, rolling_window=w)

dmap = hv.DynamicMap(rolling_means_outliers,kdims=['Exchanges','Symbols','Window']).redim.values(Exchanges=exchanges,Symbols=symbols).redim.range(Window=(2, 60))

layout = dmap * rolling_outlier_std(dmap)

renderer = renderer.instance(mode='server')

doc = renderer.server_doc(layout)
```

But I get this error thrown:

```python
Traceback (most recent call last):
  File "/home/fccoelho/Documentos/Projects_Software/Terminal/main.py", line 46, in <module>
    doc = renderer.server_doc(layout)
  File "/usr/local/lib/python3.6/dist-packages/holoviews/plotting/bokeh/renderer.py", line 197, in server_doc
    plot, _ =  renderer._validate(obj, 'auto')
  File "/usr/local/lib/python3.6/dist-packages/holoviews/plotting/renderer.py", line 208, in _validate
    plot = self.get_widget(plot, fmt, display_options={'fps': self.fps})
  File "/usr/local/lib/python3.6/dist-packages/holoviews/plotting/bokeh/renderer.py", line 129, in get_widget
    return BokehServerWidgets(plot, renderer=self_or_cls.instance(), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/holoviews/plotting/bokeh/widgets.py", line 71, in __init__
    kdims=self.dimensions)
  File "/usr/local/lib/python3.6/dist-packages/holoviews/core/ndmapping.py", line 104, in __init__
    super(MultiDimensionalMapping, self).__init__(OrderedDict(), **dict(params))
  File "/usr/local/lib/python3.6/dist-packages/holoviews/core/dimension.py", line 811, in __init__
    params.update(process_dimensions(kdims, vdims))
  File "/usr/local/lib/python3.6/dist-packages/holoviews/core/dimension.py", line 59, in process_dimensions
    dimensions[group] = [d if isinstance(d, Dimension) else Dimension(d) for d in dims]
  File "/usr/local/lib/python3.6/dist-packages/holoviews/core/dimension.py", line 59, in <listcomp>
    dimensions[group] = [d if isinstance(d, Dimension) else Dimension(d) for d in dims]
  File "/usr/local/lib/python3.6/dist-packages/holoviews/core/dimension.py", line 327, in __init__
    "consisting of the name and label not: %s" % str(spec)) 
ValueError: Dimensions specified as a tuple must be a tuple consisting of the name and label not: (Dimension('Exchanges'), Dimension('Symbols'), Dimension('Window'))
```

I am using the Bokeh backend

**Comment by philippjfr** [comment]
I believe this issue has been fixed on master. We desperately need a release soon to address these issues.
