### ISSUE TITLE
Overlay of Dynamic Maps (problem with .opts)

### ISSUE THREAD

**Issue by ClarkPennie** [ioam/holoviews#2782]
I am trying to create a tabbed overlay of dynamic maps and there seems to be an issue when I include `.opts({'plot': {'Overlay': {'tabs': True}}})`.

As an example, in the user guide section titled "Working with large data," there is the following code to create an overlay of dynamic maps:
```
import numpy as np
import pandas as pd
import holoviews as hv
from holoviews.operation.datashader import datashade, dynspread
from holoviews.operation.timeseries import rolling
hv.extension('bokeh','matplotlib')

def time_series(T = 1, N = 100, mu = 0.1, sigma = 0.1, S0 = 20):  
    """Parameterized noisy time series"""
    dt = float(T)/N
    t = np.linspace(0, T, N)
    W = np.random.standard_normal(size = N) 
    W = np.cumsum(W)*np.sqrt(dt) # standard brownian motion
    X = (mu-0.5*sigma**2)*t + sigma*W 
    S = S0*np.exp(X) # geometric brownian motion
    return S

dates = pd.date_range(start="2014-01-01", end="2016-01-01", freq='1H')
curve = hv.Curve((dates, time_series(N=len(dates), sigma = 1)))
smoothed = rolling(curve, rolling_window=50*24)
datashade(curve, cmap=["blue"]) * dynspread(datashade(smoothed, cmap=["red"]),max_px=1)
```
As soon as I change the last line to
```
(datashade(curve, cmap=["blue"]) * dynspread(datashade(smoothed, cmap=["red"]),max_px=1)).opts({'plot': {'Overlay': {'tabs': True}}})
```
I get the following error printed twice (once for each tab):
```
Traceback (most recent call last):
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/plotting/util.py", line 260, in get_plot_frame
    return map_obj[key]
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/core/spaces.py", line 1128, in __getitem__
    self._cache(tuple_key, val)
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/core/spaces.py", line 1175, in _cache
    self[key] = val
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 523, in __setitem__
    self._add_item(key, value, update=False)
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 160, in _add_item
    self._item_check(dim_vals, data)
  File "/Users/cpennie/miniconda3/lib/python3.6/site-packages/holoviews/core/ndmapping.py", line 824, in _item_check
    (self.__class__.__name__, type(data).__name__, self.type.__name__))
AssertionError: DynamicMap must only contain one type of object, not both Overlay and RGB.
```
This looks like the same error from #2284, but that issue was involving a dynamic map of overlays (the opposite of my problem) and appears to have been fixed.

Even after the errors, the tabs still show the initial plots for me but, as soon as you zoom, they disappear.

Any help on this issue would be appreciated!

**Comment by philippjfr** [comment]
The fix will be in the next release.

**Comment by ClarkPennie** [comment]
Excellent, thank you @philippjfr!
