### ISSUE TITLE
Better error messages for mismatched data and datatype?

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#2905]
If I do something wrong like this:
 
```
import holoviews as hv
shape = (100, 100)
img = hv.Image( (range(shape[1]), range(shape[0])), datatype=['grid'])
```

I get an error message like this:

```python-traceback
Traceback (most recent call last):
  File "note2.py", line 4, in <module>
    img = hv.Image( (range(shape[1]), range(shape[0])), datatype=['grid'])
  File "C:\holoviews\holoviews\element\raster.py", line 256, in __init__
    Dataset.__init__(self, data, kdims=kdims, vdims=vdims, extents=extents, **params)
  File "C:\holoviews\holoviews\core\data\__init__.py", line 231, in __init__
    datatype=kwargs.get('datatype'))
  File "C:\holoviews\holoviews\core\data\interface.py", line 194, in initialize
    if interface in head:
holoviews.core.data.interface.DataError: None of the available storage backends were able to support the supplied data format.
```

I had to stare at that for a while to realize I hadn't supplied the third dimension, rather than that e.g. I'd forgotten to install some appropriate backend.

**Comment by philippjfr** [comment]
I made one round of improvements to the data interface validation which made things a little bit better but is still far from perfect and downright terrible in many cases so there definitely needs to be more work in this regard. There are probably other cases mentioned in https://github.com/ioam/holoviews/issues/2101

**Comment by ceball** [comment]
Actually, when I look at GridInterface, I see the kind of error I'd expect: `raise ValueError("Values for dimension %s not found" % dim)` (https://github.com/ioam/holoviews/blob/master/holoviews/core/data/grid.py#L92)

I could investigate why that's not happening.

**Comment by ceball** [comment]
Sorry, didn't see that issue!

**Comment by jbednar** [comment]
Yes, this is an important problem that has bitten me several times.  It sounds like the current logic is to assume that any error in a data interface just means that it's not supported, with only a specific type of error actually reported to the user.  Can we switch that logic around so that _all_ errors are reported by default, and only a specific type of error causes it to move on to the next interface silently?  That seems like it would be a safer and more informative approach; basically, whenever we find bogus errors raised that indicate that the data interface simply doesn't support this data, then we catch those in the data interface and re-raise them as the one type of exception that causes HoloViews to move on to the next interface.  Anything else goes to the user as a real error.  Would that work?

**Comment by philippjfr** [comment]
>Can we switch that logic around so that all errors are reported by default, and only a specific type of error causes it to move on to the next interface silently?

No I really don't think so, endless things would break and it would take a long time and a lot of code to ensure things continue working as expected. As I described above errors that can be safely raised and indicate a definite error already use the ``DataError`` exception type which will be re-raised immediately.

I think we should simply write some dedicated code to pre-validate the python literal formats including tuples, dictionaries and lists.

**Comment by jbednar** [comment]
Prevalidating python literals sounds straightforward and like it will catch a lot of simple problems, so I'm all in favor of that.  

But let's say you've done that; won't there still be the same problem, i.e., endless other things that are *actual* issues with the data or how it's supported or not by the various data libraries, that the user needs to know about in order to correct them or work around them?  I.e. aren't there an untold number of exceptions that pandas, xarray, or other underlying libraries can raise that we can't really anticipate or know about, and that users can't address if they aren't given that information?

**Comment by jbednar** [comment]
Maybe the existing error message could suggest a special mode users could enter, a special flag to pass, or something like that, which would show all the exceptions raised by all the data backends considered, so that users could figure out what the real problem was?

**Comment by jlstevens** [comment]
This is a pretty tricky problem. I think I would be in favor of exposing some validation tools explicitly to the user to debug things when they have a problem. The do idea of a special debug mode might be one easy solution but I suspect figuring out what is going on when there is an error would be really tricky, even for advanced users. Alternatively, some good links to some docs detailing what the data should look like?

**Comment by philippjfr** [comment]
>Maybe the existing error message could suggest a special mode users could enter, a special flag to pass, or something like that, which would show all the exceptions raised by all the data backends considered, so that users could figure out what the real problem was?

I've considered that and it's probably a good idea, basically you'd have a ``debug`` flag or similar which simply prints the errors from all interfaces that were tried.

**Comment by philippjfr** [comment]
Or given that the default error message is basically useless maybe it should simply do that by default.

**Comment by philippjfr** [comment]
>aren't there an untold number of exceptions that pandas, xarray, or other underlying libraries can raise that we can't really anticipate or know about

This is true but there is specialized logic to handle specific types, e.g. if you pass in an xarray object it will recognize that only the xarray interface understands that data and therefore the actual error **will** be reraised. It's only in ambiguous cases, i.e. mostly the python literals, where it doesn't know which error is the most appropriate and therefore does not reraise any specific error.

**Comment by jbednar** [comment]
Ah, that makes sense.  Thanks.

Sounds like adding the explicit validation for Python literals will help a lot then, and then if the above generic error message is still reached, showing all the errors from every backend considered would do it.
