### ISSUE TITLE
HoloViews won't work with development versions of Bokeh

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#310]
HoloViews' version-parsing code appears to be failing for git versions of Bokeh that have complicated outputs from `git describe`, e.g. those with local changes or those based on git versions that aren't also releases:

```
In [1]:


import pandas as pd
import holoviews as hv
​
%reload_ext holoviews.ipython
%output backend='bokeh'
HoloViewsJS successfully loaded.
WARNING:root:Warning: Some elements and plot options are not supported by Bokeh library and backend.
BokehJS successfully loaded.
In [2]:

from holoviews.ipython import display_hooks
display_hooks.ABBREVIATE_TRACEBACKS=False
hv.Points([[0,2],[3,7]])
Traceback (most recent call last):
  File "holoviews/ipython/display_hooks.py", line 162, in wrapped
    widget_mode = widget_mode)
  File "holoviews/ipython/display_hooks.py", line 197, in element_display
    return render_plot(element_plot, False)
  File "holoviews/ipython/display_hooks.py", line 137, in render_plot
    plot.update(0)
  File "holoviews/plotting/plot.py", line 381, in update
    return self.initialize_plot()
  File "holoviews/plotting/bokeh/element.py", line 408, in initialize_plot
    plot = self._init_plot(key, ranges=ranges, plots=plots)
  File "holoviews/plotting/bokeh/element.py", line 247, in _init_plot
    major, minor = [int(v) for v  in bokeh.__version__.split('.')][0:2]
ValueError: invalid literal for int() with base 10: '0-351-g12f56e0-dirty'
Out[2]:
:Points   [x,y]
```

It works fine if I revert Bokeh to version 0.10.0.

**Comment by philippjfr** [comment]
Fixed, closing.
