### ISSUE TITLE
Verify compatibility with xarray 0.11.0

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#3159]
Our unit tests are currently failing against the newly released xarray 0.11  on at lest this unit test:

```
======================================================================
FAIL: test_datetime_bins_range (holoviews.tests.core.data.testxarrayinterface.XArrayInterfaceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ioam/holoviews/holoviews/tests/core/data/testxarrayinterface.py", line 192, in test_datetime_bins_range
    self.assertEqual(ds.range('x'), expected)
  File "/home/travis/build/ioam/holoviews/holoviews/element/comparison.py", line 79, in assertEqual
    asserter(first, second)
  File "/home/travis/build/ioam/holoviews/holoviews/element/comparison.py", line 240, in compare_tuples
    raise AssertionError(msg or '%s != %s' % (repr(t1), repr(t2)))
AssertionError: (numpy.datetime64('2017-12-31T12:00:00.000000000'), numpy.datetime64('2018-01-10T12:00:00.000000000')) != (datetime.datetime(2017, 12, 31, 12, 0), datetime.datetime(2018, 1, 10, 12, 0))
```

**Comment by philippjfr** [comment]
Done in #3433
