### ISSUE TITLE
test test_violin_empty is broken

### ISSUE THREAD

**Issue by Safrone** [ioam/holoviews#3378]
The test for empty violin plots currently throws an unexpected exception:

`tests.plotting.bokeh.testviolinplot.TestBokehViolinPlot#test_violin_empty` 
```
Error
Traceback (most recent call last):
  File "/home/holoviews/holoviews/plotting/bokeh/element.py", line 1205, in _init_glyphs
    group_style = self._apply_transforms(element, ds_data, ranges, group_style, style_group)
  File "/home/holoviews/holoviews/plotting/bokeh/stats.py", line 105, in _apply_transforms
    element = element.clone([(element.aggregate(function=np.mean),)])
  File "/home/holoviews/holoviews/core/data/__init__.py", line 852, in clone
    return super(Dataset, self).clone(data, shared_data, new_type, *args, **overrides)
  File "/home/holoviews/holoviews/core/dimension.py", line 688, in clone
    return clone_type(data, *args, **{k:v for k,v in settings.items()
  File "/home/holoviews/holoviews/core/data/__init__.py", line 210, in __init__
    datatype=kwargs.get('datatype'))
  File "/home/holoviews/holoviews/core/data/interface.py", line 236, in initialize
    (data, dims, extra_kws) = interface.init(eltype, data, kdims, vdims)
  File "/home/holoviews/holoviews/core/data/multipath.py", line 44, in init
    datatype=cls.subtypes)
  File "/home/holoviews/holoviews/core/data/interface.py", line 251, in initialize
    raise DataError(error)
holoviews.core.data.interface.DataError: None of the available storage backends were able to support the supplied data format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/home/holoviews/holoviews/tests/plotting/bokeh/testviolinplot.py", line 90, in test_violin_empty
    plot = bokeh_renderer.get_plot(violin)
  File "/home/holoviews/holoviews/plotting/bokeh/renderer.py", line 134, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
  File "/home/holoviews/holoviews/plotting/renderer.py", line 207, in get_plot
    plot.update(init_key)
  File "/home/holoviews/holoviews/plotting/plot.py", line 595, in update
    return self.initialize_plot()
  File "/home/holoviews/holoviews/plotting/bokeh/element.py", line 1049, in initialize_plot
    self._init_glyphs(plot, element, ranges, source)
  File "/home/holoviews/holoviews/plotting/bokeh/element.py", line 1205, in _init_glyphs
    group_style = self._apply_transforms(element, ds_data, ranges, group_style, style_group)
  File "/home/holoviews/holoviews/core/options.py", line 297, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: DataError: None of the available storage backends were able to support the supplied data format.
```

I believe the issue is from: https://github.com/ioam/holoviews/blob/c80f60fc64201d65495cbe2bc1a8cc25ee5bb11a/holoviews/plotting/bokeh/stats.py#L105 where the data is improperly cloned.

**Comment by philippjfr** [comment]
Thanks, wonder why the CI tests aren't picking that up.
