### ISSUE TITLE
issues with yesterday master on  Tutorials/Bokeh_Backend.ipynb on windows/python3.4

### ISSUE THREAD

**Issue by stonebig** [ioam/holoviews#399]
just a few remarks, in case you don't already know it (matplotlib1.5.1rc1, numpy 1.10.3, pandas 0.17.1,bokeh 0.11.0):

````
%%opts Scatter [tools=['box_select', 'lasso_select']] Layout [shared_axes=True shared_datasource=True]
hv.Scatter(macro_df, kdims=['year'], vdims=['gdp']) +\
hv.Scatter(macro_df, kdims=['gdp'], vdims=['unem'])
````
gives me
````
Traceback (most recent call last):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\ipython\display_hooks.py", line 101, in wrapped
    max_branches = OutputMagic.options['max_branches'])
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\ipython\display_hooks.py", line 173, in layout_display
    return render(layout)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\ipython\display_hooks.py", line 51, in render
    return Store.renderers[backend].html(obj, **kwargs)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\renderer.py", line 211, in html
    plot, fmt =  self._validate(obj, fmt)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\renderer.py", line 171, in _validate
    plot = self.get_plot(obj)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\renderer.py", line 158, in get_plot
    plot.update(0)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\plot.py", line 394, in update
    return self.initialize_plot()
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\bokeh\plot.py", line 503, in initialize_plot
    self.sync_sources()
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\holoviews\plotting\bokeh\plot.py", line 123, in sync_sources
    grouped_sources = groupby(sorted(data_sources), lambda x: x[0])
TypeError: unorderable types: PointPlot() < PointPlot()

:Layout
   .Scatter.I  :Scatter   [year]   (gdp)
   .Scatter.II :Scatter   [gdp]   (unem)
````

**Comment by stonebig** [comment]
````
%%opts Distribution (kde_kws=dict(shade=True))
d1 = np.random.randn(500) + 450
d2 = np.random.randn(500) + 540
sines = np.array([np.sin(np.linspace(0, np.pi*2, 100)) + np.random.normal(0, 1, 100) for _ in range(20)])
hv.Distribution(d1) + hv.Bivariate((d1, d2)) + hv.TimeSeries(sines)
````
gives me
````
D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\site-packages\matplotlib\axes\_axes.py:519: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
````

**Comment by stonebig** [comment]
and initial cell is missing parenthesis for Python2/3 hapiness:

````
import textwrap
from holoviews.plotting.bokeh.element import (line_properties, fill_properties,
                                              text_properties)
print ("""
      Line properties: %s\n
      Fill properties: %s\n
      Text properties: %s
      """ % (line_properties, fill_properties, text_properties))
````

**Comment by philippjfr** [comment]
Thanks for reporting these. We haven't yet implemented testing for Bokeh Tutorials so that notebook has never been run with Python3. I think the first issue can be fixed by using:

```
    grouped_sources = groupby(sorted(data_sources, lambda x: x[0]), lambda x: x[0])
```

The second issue is something to do with empty legend labels in the seaborn plots.

**Comment by stonebig** [comment]
you mean a bokeh 0.11 bug ?

**Comment by philippjfr** [comment]
No it's our bug, will submit a fix before 1.4.2.

**Comment by philippjfr** [comment]
I've fixed the bugs you mentioned in 673e2b827b7c8e32a9c2412c356e34ea10653ea6 and fcaa702b2f4bfac0cbe6a9831c8dd663948f0bb6. Closing.

**Comment by stonebig** [comment]
Now, situation looks not ok:
- I get external references and failures:
````
Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.min.css
2

bokeh-0.11.0.min.js:63 Bokeh: LogTickFormatter not configured with a ticker, using default base of 10 (labels will be incorrect if ticker base is not 10)
bokeh-0.11.0.min.js:4 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

Uncaught RuntimeError: RuntimeError:Program validation error https://cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.js
````
I suppose it's Bokeh being in moving state ?

**Comment by stonebig** [comment]
is there an option `webgl=False` available somewhere ? I see you may turn it on by default for bokeh
````
        if LooseVersion(bokeh.__version__) >= LooseVersion('0.10'):
            properties['webgl'] = True
````
