### ISSUE TITLE
reload(sys) and help

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#421]
When trying to use unicode characters in plots, the hv.help functions breaks down.

To use unicode I add the following lines to my notebook:
```python
from __future__ import unicode_literals, division
import sys; reload(sys)
sys.setdefaultencoding("utf-8")
```

However, the reload(sys) breaks the help, hv.help is not shown in the browser, but in the terminal where jupyter notebook is running

Works:
```python
from __future__ import unicode_literals, division
import sys
%matplotlib inline
import holoviews as hv
hv.notebook_extension()
hv.help(hv.Image)
```

Does not work:
```python
from __future__ import unicode_literals, division
import sys; reload(sys)
%matplotlib inline
import holoviews as hv
hv.notebook_extension()
hv.help(hv.Image)
```

**Comment by jlstevens** [comment]
If I remember, people use ``reload(sys)`` to set unicode in Python 2. I assume that is what you are doing...

Have you tried setting the ``PYTHONIOENCODING`` environment variable to ```'utf8'``? Then you could just stick it into your bashrc and not worry about doing this in Python all the time.

**Comment by vascotenner** [comment]
When setting the PYTHONIOENCODING environment variable to 'utf8' I can print unicode characters, however, I cannot create plots with unicode characters:

```hv.Points([1,1], kdims=['x',hv.Dimension('γ', unit='α')])```

```python
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.pyc in __call__(self, obj)
    695                 type_pprinters=self.type_printers,
    696                 deferred_pprinters=self.deferred_printers)
--> 697             printer.pretty(obj)
    698             printer.flush()
    699             return stream.getvalue()

/usr/local/lib/python2.7/dist-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    381                             if callable(meth):
    382                                 return meth(obj, self, cycle)
--> 383             return _default_pprint(obj, self, cycle)
    384         finally:
    385             self.end_group()

/usr/local/lib/python2.7/dist-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    502         # A user-provided repr. Find newlines and replace them with p.break_()
--> 503         _repr_pprint(obj, p, cycle)
    504         return
    505     p.begin_group(1, '<')

/usr/local/lib/python2.7/dist-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    683     """A pprint that just redirects to the normal repr function."""
    684     # Find newlines and replace them with p.break_()
--> 685     output = repr(obj)
    686     for idx,output_line in enumerate(output.splitlines()):
    687         if idx:

UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b3' in position 13: ordinal not in range(128)

Traceback (most recent call last):
  File "/home/a/src/holoviews/holoviews/ipython/display_hooks.py", line 101, in wrapped
    max_branches = OutputMagic.options['max_branches'])
  File "/home/a/src/holoviews/holoviews/ipython/display_hooks.py", line 150, in element_display
    return renderer.html(element, fmt=renderer.fig)
  File "/home/a/src/holoviews/holoviews/plotting/renderer.py", line 211, in html
    plot, fmt =  self._validate(obj, fmt)
  File "/home/tenner/src/holoviews/holoviews/plotting/renderer.py", line 171, in _validate
    plot = self.get_plot(obj)
  File "/home/a/src/holoviews/holoviews/plotting/renderer.py", line 158, in get_plot
    plot.update(0)
  File "/home/a/src/holoviews/holoviews/plotting/mpl/plot.py", line 208, in update
    return self.initialize_plot()
  File "/home/a/src/holoviews/holoviews/plotting/mpl/chart.py", line 581, in initialize_plot
    return self._finalize_axis(self.keys[-1], ranges=ranges)
  File "/home/a/src/holoviews/holoviews/plotting/mpl/element.py", line 146, in _finalize_axis
    xlabel, ylabel, zlabel = self._axis_labels(element, subplots, xlabel, ylabel, zlabel)
  File "/home/a/src/holoviews/holoviews/plotting/plot.py", line 549, in _axis_labels
    ylabel = util.safe_unicode(str(dims[1]))
  File "/home/a/src/holoviews/holoviews/core/dimension.py", line 173, in __str__
    return self.pprint_label
  File "/home/a/src/holoviews/holoviews/core/dimension.py", line 125, in pprint_label
    unit = '' if self.unit is None else self.unit_format.format(unit=self.unit)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b1' in position 0: ordinal not in range(128)
```

 I am running IPython (4, 0, 3, '')

**Comment by philippjfr** [comment]
Ah, that's something we'll have to fix. I'll do some testing to see what happens if I just put ``from __future__ import unicode_literals`` at the top of dimension.py.

**Comment by jlstevens** [comment]
I can't even run as much as ``import sys;reload(sys)`` without having my print statement stop working entirely ([see this thread on stackoverflow](http://stackoverflow.com/questions/13438299/python-print-doesnt-work-after-sys-setdefaultencodingutf-8). For this reason, I can't even begin to try to get that approach working.

Instead, I'll look into what is going wrong if ``PYTHONIOENCODING`` is set to ``'utf8'``...

**Comment by jlstevens** [comment]
When I launch IPython using:

```
PYTHONIOENCODING=utf8 ipython notebook
```

I find this works fine:

```python
import holoviews as hv
hv.notebook_extension()

hv.Points([1,1], kdims=['x',hv.Dimension('γ', unit='α')])
```

Although the greek letters are rendered as little boxes unless I use this instead (i.e a font that supports these letters):

```python
import matplotlib
matplotlib.rc('font', family='Arial')
hv.Points([1,1], kdims=['x',hv.Dimension('γ', unit='α')])
```

However, if I run ``from __future__ import unicode_literals`` anywhere in my notebook, I see the same error:

```python
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b1' in position 0: ordinal not in range(128)
```

So one solution is to avoid importing ``unicode_literals`` though I suppose you might want that for some other code. I'll open a PR very shortly to try and fix that.

**Comment by jlstevens** [comment]
I believe this issue has now been fixed in the PR mentioned above (now merged).
