### ISSUE TITLE
Robustness against problems with optional dependencies

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#732]
HoloViews has recently added support for using data formats defined by the optional external Iris library, which uses cartopy.  On my system at the moment, those libraries are broken because of having to downgrade numpy to try out some older software.  I wouldn't otherwise be concerned about that, but it's breaking HoloViews import (see transcript below).  Even though HoloViews will work fine if iris and cartopy aren't installed at all, it's only catching ImportError, and here a ValueError is being thrown.  

I propose that for optional libraries like Iris, Cartopy, Pandas, and xarray, we silently ignore ImportErrors (since those suggest the library simply isn't installed), but non-silently ignore other errors (showing the usual error and backtrace information, but not aborting).

```python
$ python
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import holoviews
RuntimeError: module compiled against API version a but this version of numpy is 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "holoviews/__init__.py", line 14, in <module>
    from .core import archive                               # noqa (API import)
  File "holoviews/core/__init__.py", line 2, in <module>
    from .data import *            # noqa (API import)
  File "holoviews/core/data/__init__.py", line 29, in <module>
    import iris # noqa (Availability import)
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/__init__.py", line 110, in <module>
    import iris.cube
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/cube.py", line 39, in <module>
    import iris.analysis
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/analysis/__init__.py", line 61, in <module>
    from iris.analysis._area_weighted import AreaWeightedRegridder
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/analysis/_area_weighted.py", line 23, in <module>
    from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/analysis/_interpolation.py", line 31, in <module>
    from iris.analysis.cartography import wrap_lons as wrap_circular_points
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/Iris-1.10.0.dev0-py2.7.egg/iris/analysis/cartography.py", line 33, in <module>
    import cartopy.img_transform
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/cartopy/__init__.py", line 110, in <module>
    import cartopy.crs
  File "/Users/jbednar/anaconda/lib/python2.7/site-packages/cartopy/crs.py", line 37, in <module>
    from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_RELEASE
  File "__init__.pxd", line 155, in init cartopy._crs (lib/cartopy/_crs.c:11291)
ValueError: numpy.dtype has the wrong size, try recompiling
```

**Comment by jlstevens** [comment]
Now the PR is merged, can this issue be closed?
