### ISSUE TITLE
Error Export Bokeh figure with Python 3.5

### ISSUE THREAD

**Issue by hervo63** [ioam/holoviews#979]
Hi, 

There is the following error when I am trying to export an HTML image with Python 3.5 (holoviews 1.6.2)

```python
import numpy as np
import holoviews as hv
hv.notebook_extension(bokeh=True)

x,y = np.meshgrid(np.linspace(-5,5,101), np.linspace(5,-5,101))
test=hv.Raster(np.sin(x**2+y**2))

renderer = hv.Store.renderers['bokeh'].instance(fig='html');
renderer.save(test, 'example_I')
```
I have the following error:
```python
renderer.save(test, 'example_I')
Traceback (most recent call last):

  File "<ipython-input-19-7e2a8a193726>", line 2, in <module>
    renderer.save(test, 'example_I')

  File "C:\Work\Anaconda\lib\site-packages\holoviews\plotting\renderer.py", line 467, in save
    f.write(encoded)

TypeError: a bytes-like object is required, not 'str'
```
it is working just fine on Python 2.7

Is there a work around for Python 3.5 ?
Thanks

**Comment by jlstevens** [comment]
Thanks for reporting this!

It should definitely work the same on Python 3.5 as 2.7 so this is a bug.
